name: 2FA
description: A plugin that adds another layer of protection for your players
authors: [LielAmar, xItsRaz]
version: 1.0
main: com.lielamar.auth.Main

commands:
  2fa:
    description: Setup your 2FA app/Enter your 2FA code
    aliases: [auth]

permissions:
  2fa.*:
    description: Permissions to all 2FA commands
    default: op
    children:
      2fa.use: true
      2fa.setup: true
      2fa.remove: true
      2fa.admin: true
  2fa.use:
    description: Permissions to use the /2FA command
    default: op
  2fa.setup:
    description: Permissions to set up 2FA
    default: op
  2fa.remove:
    description: Permissions to remove your own 2FA
    default: op
  2fa.admin:
    description: Admin permissions to remove other players' 2FA
    default: op
  2fa.exampt:
    description: Exampt from using 2FA
    default: false