name: 2FA
description: A plugin that adds another layer of protection for your players
authors: [LielAmar, xItsRaz]
version: 1.0
main: com.lielamar.auth.Main

commands:
  2fa:
    description: Two Factor Authentication
    aliases: [auth]
  2faadmin:
    description: Two Factor Authentication Admin Command
    aliases: [authadmin]

permissions:
  2fa.*:
    description: Permissions to all 2FA commands
    default: op
    children:
      2fa.use: true
      2fa.setup: true
      2fa.remove: true
      2fa.remove.others: true
      2fa.reload: true
  2fa.use:
    description: Permissions to use the /2FA command
    default: op
  2fa.setup:
    description: Permissions to set up 2FA
    default: op
  2fa.remove:
    description: Permissions to remove your own 2FA
    default: op
  2fa.remove.others:
    description: Admin permissions to remove other players' 2FA
    default: op
  2fa.reload:
    description: Admin permissions to reload the 2FA plugin
    default: op
  2fa.demand:
    description: A player with this permission must have 2FA linked to thier account
    default: false
  2fa.exempt:
    description: A player with this permission does not have to authenticate
    default: false